name: Newsletter Cron

on:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  SendMail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Send the newsletter
        run: |
          export YESTERDAY_DATE=$(date -d "yesterday" '+%Y-%m-%d')
          python3 main.py --date=${YESTERDAY_DATE} --from=${SMTP_FROM} --pass=${SMTP_PASS} --to=${SMTP_TO}
        env:
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_TO: ${{ secrets.SMTP_TO }}